### ISSUE TITLE
Item Window Will not Open

### ISSUE THREAD

**Issue by ScottUlmer** [misterpotts/fabricate#69]
## Describe the bug

When I go to Items → Crafting Systems it does not do anything.

## To Reproduce

1. Go to Items
2. Click on Crafting Systems

## Expected behavior

[A clear and concise description of what you expected to happen.](https://github.com/misterpotts/fabricate/raw/main/screens/fabricate-system-creation.gif)

## Screenshots

![image](https://user-images.githubusercontent.com/29180106/210412961-f9a5e8f5-2e6b-43a3-8740-cb113d7ef797.png)

https://user-images.githubusercontent.com/29180106/210413114-bc1f5350-4208-4b5b-969e-8b7926ba2a4c.mp4

![image](https://user-images.githubusercontent.com/29180106/210413367-ec2d9045-9e39-4f15-9909-83354e477735.png)

## Version information

- Foundry version: [e.g. 10]
- Fabricate version: [e.g. 0.7.2]

## Additional context

I am running on FATE which is not one of the "big" rule-sets but I don't think that could cause it.

**Comment by ScottUlmer** [comment]
I can confirm it works on D&D but not FATE.

**Comment by misterpotts** [comment]
That's fun! Thanks for the report 🐛 

I suspect that it is trying to load Alchemist's Supplies, which depends on 5E. The system data is good, so it's looking for the compendium Items. I don't think foundry is loading them, as the compendium also depends upon 5E.

This can be fixed in a few ways:

1. Loading crafting systems and not displaying those that fail, or showing them as being in error in the UI
2. Tagging systems with the game system they are created in, and then not loading them if the game system isn't present

Arguably I could do both.

**Comment by ScottUlmer** [comment]
Is there anything else I can do to help you? And thanks again for your support your add-in is pretty awesome.

**Comment by misterpotts** [comment]
That's all the information I need to work the Issue, thanks! The only thing I could ask for above and beyond than this excellent, detailed bug report is the code to fix the issue 😉

**Comment by misterpotts** [comment]
The fix is simpler than I first thought in one way, but more complex in another.

The way I'm going about solving it is to no longer store bundled systems in world data. That wasn't necessary, as the data ships with the module and cannot be edited. This requires:

1. Deleting copies of alchemist's supplies in world data on startup 
2. A change to system duplication to use the data in memory, rather than in world settings
3. Combining bundled system data and stored data when loading all systems
4. Filtering out bundled systems with game system dependencies

I'm pretty optimistic about getting this sorted quickly though. Will keep you updated.

**Comment by misterpotts** [comment]
![image](https://user-images.githubusercontent.com/17074386/210507560-c5e444f0-5f3b-4360-8f0c-8475818441a7.png)

Now opening in `pf2e`.

![image](https://user-images.githubusercontent.com/17074386/210507791-7464af40-ee1f-4a68-ad56-b50db4188d89.png)

And in `fate-core-official`

![image](https://user-images.githubusercontent.com/17074386/210509501-26151ea0-812b-4e74-8ddd-860f0ac9af5b.png)

And in `dnd5e`, where Alchemist's Supplies v1.6 is no longer stored in world settings:

![image](https://user-images.githubusercontent.com/17074386/210510388-0dd4f2de-efc1-4063-95ba-319054c7c723.png)

But there's another minor, unrelated issue to resolve now. It won't (or should not) impact you and is described in #73
